# Form implementation generated from reading ui file 'bezier_curve_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BezierCurveDialog(object):
    def setupUi(self, BezierCurveDialog):
        BezierCurveDialog.setObjectName("BezierCurveDialog")
        BezierCurveDialog.resize(555, 492)
        self.verticalLayout = QtWidgets.QVBoxLayout(BezierCurveDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=BezierCurveDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.canvasFrame = QtWidgets.QFrame(parent=self.frame)
        self.canvasFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.canvasFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.canvasFrame.setObjectName("canvasFrame")
        self.horizontalLayout.addWidget(self.canvasFrame)
        self.dataFrame = QtWidgets.QFrame(parent=self.frame)
        self.dataFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dataFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dataFrame.setObjectName("dataFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dataFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.levelFrame = QtWidgets.QFrame(parent=self.dataFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.levelFrame.sizePolicy().hasHeightForWidth())
        self.levelFrame.setSizePolicy(sizePolicy)
        self.levelFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.levelFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.levelFrame.setObjectName("levelFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.levelFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.levelLabel = QtWidgets.QLabel(parent=self.levelFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.levelLabel.sizePolicy().hasHeightForWidth())
        self.levelLabel.setSizePolicy(sizePolicy)
        self.levelLabel.setObjectName("levelLabel")
        self.horizontalLayout_2.addWidget(self.levelLabel)
        self.levelSpinBox = QtWidgets.QSpinBox(parent=self.levelFrame)
        self.levelSpinBox.setMinimum(1)
        self.levelSpinBox.setMaximum(10)
        self.levelSpinBox.setObjectName("levelSpinBox")
        self.horizontalLayout_2.addWidget(self.levelSpinBox)
        self.verticalLayout_2.addWidget(self.levelFrame)
        self.pointsFrame = QtWidgets.QFrame(parent=self.dataFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointsFrame.sizePolicy().hasHeightForWidth())
        self.pointsFrame.setSizePolicy(sizePolicy)
        self.pointsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pointsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pointsFrame.setObjectName("pointsFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pointsFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pointsLabel = QtWidgets.QLabel(parent=self.pointsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointsLabel.sizePolicy().hasHeightForWidth())
        self.pointsLabel.setSizePolicy(sizePolicy)
        self.pointsLabel.setObjectName("pointsLabel")
        self.verticalLayout_3.addWidget(self.pointsLabel)
        self.drawedPointsFrame = QtWidgets.QFrame(parent=self.pointsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawedPointsFrame.sizePolicy().hasHeightForWidth())
        self.drawedPointsFrame.setSizePolicy(sizePolicy)
        self.drawedPointsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.drawedPointsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.drawedPointsFrame.setObjectName("drawedPointsFrame")
        self.verticalLayout_3.addWidget(self.drawedPointsFrame)
        self.verticalLayout_2.addWidget(self.pointsFrame)
        self.horizontalLayout.addWidget(self.dataFrame)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=BezierCurveDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(BezierCurveDialog)
        self.buttonBox.accepted.connect(BezierCurveDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(BezierCurveDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BezierCurveDialog)

    def retranslateUi(self, BezierCurveDialog):
        _translate = QtCore.QCoreApplication.translate
        BezierCurveDialog.setWindowTitle(_translate("BezierCurveDialog", "Dialog"))
        self.levelLabel.setText(_translate("BezierCurveDialog", "Stopień n:"))
        self.pointsLabel.setText(_translate("BezierCurveDialog", "Punkty:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BezierCurveDialog = QtWidgets.QDialog()
    ui = Ui_BezierCurveDialog()
    ui.setupUi(BezierCurveDialog)
    BezierCurveDialog.show()
    sys.exit(app.exec())
