# Form implementation generated from reading ui file 'pixel_analysis_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PixelAnalysisDialog(object):
    def setupUi(self, PixelAnalysisDialog):
        PixelAnalysisDialog.setObjectName("PixelAnalysisDialog")
        PixelAnalysisDialog.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PixelAnalysisDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=PixelAnalysisDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.image = QtWidgets.QLabel(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image.setObjectName("image")
        self.verticalLayout_4.addWidget(self.image)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hsvFrame = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hsvFrame.sizePolicy().hasHeightForWidth())
        self.hsvFrame.setSizePolicy(sizePolicy)
        self.hsvFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.hsvFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.hsvFrame.setObjectName("hsvFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.hsvFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hueLabel = QtWidgets.QLabel(parent=self.hsvFrame)
        self.hueLabel.setObjectName("hueLabel")
        self.verticalLayout_3.addWidget(self.hueLabel)
        self.hueSlider = QRangeSlider(parent=self.hsvFrame)
        self.hueSlider.setObjectName("hueSlider")
        self.verticalLayout_3.addWidget(self.hueSlider)
        self.hueColorLabel = QtWidgets.QLabel(parent=self.hsvFrame)
        self.hueColorLabel.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 rgba(255, 0, 0, 255), \n"
"        stop:0.166 rgba(255, 255, 0, 255), \n"
"        stop:0.333 rgba(0, 255, 0, 255), \n"
"        stop:0.5 rgba(0, 255, 255, 255), \n"
"        stop:0.666 rgba(0, 0, 255, 255), \n"
"        stop:0.833 rgba(255, 0, 255, 255), \n"
"        stop:1 rgba(255, 0, 0, 255));\n"
"    border-radius: 5px; \n"
"}")
        self.hueColorLabel.setText("")
        self.hueColorLabel.setObjectName("hueColorLabel")
        self.verticalLayout_3.addWidget(self.hueColorLabel)
        self.saturationLabel = QtWidgets.QLabel(parent=self.hsvFrame)
        self.saturationLabel.setObjectName("saturationLabel")
        self.verticalLayout_3.addWidget(self.saturationLabel)
        self.saturationSlider = QRangeSlider(parent=self.hsvFrame)
        self.saturationSlider.setObjectName("saturationSlider")
        self.verticalLayout_3.addWidget(self.saturationSlider)
        self.brightnessLabel = QtWidgets.QLabel(parent=self.hsvFrame)
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.verticalLayout_3.addWidget(self.brightnessLabel)
        self.brightnessSlider = QRangeSlider(parent=self.hsvFrame)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.verticalLayout_3.addWidget(self.brightnessSlider)
        self.verticalLayout.addWidget(self.hsvFrame)
        self.resultsFrame = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsFrame.sizePolicy().hasHeightForWidth())
        self.resultsFrame.setSizePolicy(sizePolicy)
        self.resultsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultsFrame.setObjectName("resultsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.resultsFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.biggestAreaLabel = QtWidgets.QLabel(parent=self.resultsFrame)
        self.biggestAreaLabel.setObjectName("biggestAreaLabel")
        self.gridLayout.addWidget(self.biggestAreaLabel, 1, 0, 1, 1)
        self.globalLabel = QtWidgets.QLabel(parent=self.resultsFrame)
        self.globalLabel.setObjectName("globalLabel")
        self.gridLayout.addWidget(self.globalLabel, 0, 0, 1, 1)
        self.globalValueLabel = QtWidgets.QLabel(parent=self.resultsFrame)
        self.globalValueLabel.setText("")
        self.globalValueLabel.setObjectName("globalValueLabel")
        self.gridLayout.addWidget(self.globalValueLabel, 0, 1, 1, 1)
        self.biggestAreaValueLabel = QtWidgets.QLabel(parent=self.resultsFrame)
        self.biggestAreaValueLabel.setText("")
        self.biggestAreaValueLabel.setObjectName("biggestAreaValueLabel")
        self.gridLayout.addWidget(self.biggestAreaValueLabel, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.resultsFrame)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PixelAnalysisDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(PixelAnalysisDialog)
        self.buttonBox.accepted.connect(PixelAnalysisDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(PixelAnalysisDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PixelAnalysisDialog)

    def retranslateUi(self, PixelAnalysisDialog):
        _translate = QtCore.QCoreApplication.translate
        PixelAnalysisDialog.setWindowTitle(_translate("PixelAnalysisDialog", "Dialog"))
        self.hueLabel.setText(_translate("PixelAnalysisDialog", "Odcień:"))
        self.saturationLabel.setText(_translate("PixelAnalysisDialog", "Nasycenie:"))
        self.brightnessLabel.setText(_translate("PixelAnalysisDialog", "Jasność:"))
        self.biggestAreaLabel.setText(_translate("PixelAnalysisDialog", "Najw. obszar: "))
        self.globalLabel.setText(_translate("PixelAnalysisDialog", "Globalnie:"))
from superqt import QRangeSlider


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PixelAnalysisDialog = QtWidgets.QDialog()
    ui = Ui_PixelAnalysisDialog()
    ui.setupUi(PixelAnalysisDialog)
    PixelAnalysisDialog.show()
    sys.exit(app.exec())
